ccflags-y += -Wno-error
#include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
# Makefile for Bosch sensor driver.
#
obj-y +=  bhy_acc.o bstclass.o

