ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/bhy_acc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/pick_up_sensor
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/bhy
obj-y	:=  bhy_gesture.o

