
# In case the platform does NOT support this type of sensors

obj-$(CONFIG_LEDS_RT4832) += rt4832/
obj-$(CONFIG_LEDS_DW8767) += dw8767/
obj-$(CONFIG_LEDS_LM3648) += lm3648/
obj-$(CONFIG_LEDS_LM3632) += lm3632/
obj-$(CONFIG_LEDS_DW8767_CV7A) += dw8767_cv7a/
obj-$(CONFIG_LEDS_RT4832_LV5) += rt4832_lv5/
obj-$(CONFIG_LEDS_DW8767_CV1) += dw8767_cv1/