ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/bmi160-new
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation
obj-y	:=  bmi160_stc.o

