ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
obj-y	:=  icm406xx_accel.o
obj-y	+=  icm406xx_share.o
obj-y	+=  icm406xx_share_interface.o
