ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-0.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-0.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-0.0/mach
obj-y	:=  k303b-acc-new.o
