ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-0.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-0.0/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-0.0/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-0.0/magnetometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-0.0/barometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-0.0/humidity/inc
obj-y := sensor_dts.o
